spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
      #bootstrap-servers are the kafka brokers. 
      #You can mention all or one of them. 
      #It is better to list all the brokers in the cluster.
    template:
      default-topic: first-topic
      #We would be writing messages into a topic. 
      #So create a topic called random-number in your kafka cluster.
      #The producer itself would create the topic if it is not present.
      #However it would go with default values like 1 partition which you might not want.
      #Usually it is better to create these topics upfront in your cluster.
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      #The messages could be key-value pairs.
      #Key is optional and can be omitted.
      #(It is recommended to use keys).
      #Key and value serializers indicate the types of Key and value.